### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [zneak/fcd#10]
I would like to point out that identifiers like "[`fcd__metadata_h`](https://github.com/zneak/fcd/blob/1940d9c15cbaef1bbc2fc4eb87539103518e263b/fcd/metadata.h#L22)" and "[`fcd__targetinfo_h`](https://github.com/zneak/fcd/blob/3491325fbc9cfb7a8ed826aa94ef4a1ed48cd9be/fcd/targetinfo.h#L22)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by zneak** [comment]
Pragmatically, I'm not particularly worried that any of these are ever going to conflict with anything and I don't plan on changing it. I probably wouldn't reject a PR that does it though.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by zneak** [comment]
I'll change it myself if you can find a single C++14 compiler where this actually matters. I'll still take PRs if they come my way.

**Comment by Trass3r** [comment]
Nowadays every big compiler supports `#pragma once` anyway, which does away with the whole problem.

**Comment by elfring** [comment]
Do you care for [standard compliance](http://stackoverflow.com/questions/23696115/is-pragma-once-part-of-the-c11-standard/23699893#23699893 "Is #pragma once part of the C++11 standard?")?

**Comment by zneak** [comment]
I care about and work for things that have a practical impact. I prefer compliance over non-compliance, but I'm not interested in spending any of my own time to do things that have no practical value.
