### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [zneak/fcd#11]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/zneak/fcd/blob/be47edc73e554a2ec4600f6964766fdd99678362/fcd/main.cpp#L504 "main() function")" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108 "Uncaught exceptions") like they are described by Danny Kalev?

**Comment by zneak** [comment]
It does not contain any because fcd does not throw any. LLVM needs to be built with `-fno-exceptions`, so even if I wanted to throw exceptions myself, it would be unsafe to do so. As a consequence, fcd also compiles with `-fno-exceptions`.

**Comment by Trass3r** [comment]
One of the best things about the llvm codebase. No exceptions and no RTTI.
