### ISSUE TITLE
make failed on Ubuntu 14.04

### ISSUE THREAD

**Issue by HirumaStu** [zneak/fcd#12]
When I tried to build master I got the error:
bindings.cpp:2091:20: error: no matching function for call to 'LLVMBuildLandingPad'
        auto callReturn = LLVMBuildLandingPad(self->obj, arg0->obj, arg1, arg2);
It has been checked on gcc 4.8 and 5.3.0, (llvm/clang)-3.7

**Comment by zneak** [comment]
You have LLVM 3.7.1, which broke API compatibility with 3.7.

There are a couple of options, but the simplest one would be to replace the offending line with something like "LLVMValueRef callReturn = nullptr;", since fcd doesn't use landing pads anyway.

**Comment by zneak** [comment]
This will be fixed soon-ish when LLVM 3.8 lands.
