### ISSUE TITLE
Partial pipeline execution fails with errors but if the pipeline runs completely no problems occur

### ISSUE THREAD

**Issue by Lukas-Dresel** [zneak/fcd#23]
I've been trying to understand what all the different passes in the default pipeline do. To that end I ran fcd with a partial pipeline on Ubuntu 16.04's `/bin/ls`, specifically with

`fcd -opt-pipeline="globaldce fixindirects" /bin/ls`

This gives me the following errors:
`
IntToPtr result must be a pointer
  %8 = inttoptr i64 %7 to i64
IntToPtr result must be a pointer
  %8 = inttoptr i64 %7 to i64
`

However if i run fcd normally with only `fcd /bin/ls` everything works fine.
Why does this happen? Do the passes leave the LLVM representation in invalid states?

**Comment by Lukas-Dresel** [comment]
Then when i thought the problem was that the code cannot be decompiled at that stage since no analysis has been performed yet i attempted to run
`fcd -n -n -n -opt-pipeline="globalcde fixindirects" /bin/ls`
And that also produces the errors. 

Is there any way i can produce the LLVM representation and then see only the effects of single passes?

**Comment by zneak** [comment]
You may find [this page](http://zneak.github.io/fcd/2016/03/16/bugpoint.html) valuable for what you're trying to do.

This is admittedly hard (I've long been the only person interested in this, it seems) and the simplest way to do that might be to put a breakpoint at the end of the pass. Another option could be to insert a `print-module` pass where you need it.

**Comment by Lukas-Dresel** [comment]
Okay, so I chose the print-module way of doing it as you can see in my fork in the branch pipeline-testing. This seems to do what i want it to for now. Thanks for the help!

**Comment by Lukas-Dresel** [comment]
This definitely helps finding unreasonable things for now, expect issues ;)
Meanwhile i'll close this issue to keep the relevant issues up-to-date.

**Comment by zneak** [comment]
Awesome! But please note that fcd started as a school project, and now I've graduated and I work full-time. I'll do my best to fix bugs but I can't just spend the whole day working on fcd anymore.
