### ISSUE TITLE
nullptr dereference

### ISSUE THREAD

**Issue by Trass3r** [zneak/fcd#35]
Nice catch by clang static analyzer in https://github.com/zneak/fcd/blob/master/fcd/callconv/anyarch_anycc.cpp#L179:
```
 5: Assuming 'load' is non-null in anyarch_anycc.cpp:146
 6: 'load' initialized to a null pointer value in anyarch_anycc.cpp:179
 7: Called C++ object pointer is null in anyarch_anycc.cpp:181
```
Also shows -Werror=shadow would be good.

**Comment by zneak** [comment]
It's worth fixing, but anyarch_anycc is terribly broken and can't be used with most of fcd's newer and nicer features around calling conventions.
