### ISSUE TITLE
print declarations where they happen instead of function start

### ISSUE THREAD

**Issue by Trass3r** [zneak/fcd#4]
Like in C99/C++ vs. older C.
Just tested a quick hack removing the decl block and adding the type to the token returned by `FunctionNode::createDeclaration(Type &type, const string& declName)`.
Already better, but of course also affects further usages. DeclarationStatement would need to be transformed somehow.

btw very nifty approach using a normal emulator instead of the usual cumbersome llvm API code :+1:

**Comment by zneak** [comment]
The problem with declaring them inline is that there's no guarantee that the first assignment happens visually before the first use, or even in a compatible scope. You could end up with something like:

```
while (foo)
{
	if (bar)
	{
		baz += 5;
	}
	else
	{
		int baz = 4;
	}
}
```

I'm in favor of the feature, and it's not impossible to overcome this, but it's much more effort than just "move this line elsewhere" and there are things that are more important to me at the moment.

**Comment by Trass3r** [comment]
I see, thanks for the example.

**Comment by zneak** [comment]
By the way, I had to do away with declaration nodes in the ast-uses branch, so while I was at it I implemented support for this. (ast-uses is still in a very rudimentary state, no AST pass compiles yet except the printing one.)
