### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by kika123** [zneak/fcd#7]

**Comment by kika123** [comment]
Windows has some non-standard register behavour, especially in the FS and GS registers

**Comment by kika123** [comment]
and int and longs are 32bit on Windows, even on 64bit systems

**Comment by zneak** [comment]
Which problem are we trying to address here? Decompiling Windows programs or running fcd on Windows?

**Comment by kika123** [comment]
decompiling Windows programs

**Comment by zneak** [comment]
There are lots of issues to consider before even thinking about what `gs` and `fs` mean on Windows. The first step would be to have a PE parser and some calling convention support.
